Upgrade to es6 t. deal w. following bug:
 error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.